import { CampaignItemCategoryRuleRepository } from '#repositories/campaign_item_category_rule_repository'
import type CampaignItemCategoryRule from '#models/campaign_item_category_rule'

interface CategorySeed {
  category: 'spell' | 'feature' | 'inventory'
  subcategory: string
  itemType: string
  matchField: string | null
  matchValue: string | null
  label: string
  icon: string | null
  color: string | null
  isTargetable: boolean
  weight: number
  priority: number
}

/**
 * Pre-configured category mappings per RPG system.
 * Keys are Foundry VTT system IDs (e.g. 'dnd5e', 'pf2e').
 */
export const SYSTEM_MAPPINGS: Record<string, CategorySeed[]> = {
  // ────────────────────────────────────────
  // D&D 5th Edition
  // ────────────────────────────────────────
  'dnd5e': [
    // Spells — by school
    {
      category: 'spell',
      subcategory: 'cantrip',
      itemType: 'spell',
      matchField: 'system.level',
      matchValue: '0',
      label: 'Cantrips',
      icon: 'sparkles',
      color: '#A78BFA',
      isTargetable: false,
      weight: 1,
      priority: 10,
    },
    {
      category: 'spell',
      subcategory: 'abjuration',
      itemType: 'spell',
      matchField: 'system.school',
      matchValue: 'abj',
      label: 'Abjuration',
      icon: 'shield',
      color: '#60A5FA',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'spell',
      subcategory: 'conjuration',
      itemType: 'spell',
      matchField: 'system.school',
      matchValue: 'con',
      label: 'Conjuration',
      icon: 'ghost',
      color: '#34D399',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'spell',
      subcategory: 'divination',
      itemType: 'spell',
      matchField: 'system.school',
      matchValue: 'div',
      label: 'Divination',
      icon: 'eye',
      color: '#FBBF24',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'spell',
      subcategory: 'enchantment',
      itemType: 'spell',
      matchField: 'system.school',
      matchValue: 'enc',
      label: 'Enchantement',
      icon: 'heart',
      color: '#F472B6',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'spell',
      subcategory: 'evocation',
      itemType: 'spell',
      matchField: 'system.school',
      matchValue: 'evo',
      label: 'Évocation',
      icon: 'flame',
      color: '#EF4444',
      isTargetable: true,
      weight: 2,
      priority: 5,
    },
    {
      category: 'spell',
      subcategory: 'illusion',
      itemType: 'spell',
      matchField: 'system.school',
      matchValue: 'ill',
      label: 'Illusion',
      icon: 'palette',
      color: '#C084FC',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'spell',
      subcategory: 'necromancy',
      itemType: 'spell',
      matchField: 'system.school',
      matchValue: 'nec',
      label: 'Nécromancie',
      icon: 'skull',
      color: '#6B7280',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'spell',
      subcategory: 'transmutation',
      itemType: 'spell',
      matchField: 'system.school',
      matchValue: 'trs',
      label: 'Transmutation',
      icon: 'rotate-cw',
      color: '#FB923C',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },

    // Features
    {
      category: 'feature',
      subcategory: 'class_feature',
      itemType: 'feat',
      matchField: 'system.type.value',
      matchValue: 'class',
      label: 'Capacités de classe',
      icon: 'swords',
      color: '#8B5CF6',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'feature',
      subcategory: 'racial_trait',
      itemType: 'feat',
      matchField: 'system.type.value',
      matchValue: 'race',
      label: 'Traits raciaux',
      icon: 'dna',
      color: '#14B8A6',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'feature',
      subcategory: 'feat',
      itemType: 'feat',
      matchField: 'system.type.value',
      matchValue: 'feat',
      label: 'Dons',
      icon: 'award',
      color: '#F59E0B',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },

    // Inventory
    {
      category: 'inventory',
      subcategory: 'weapon',
      itemType: 'weapon',
      matchField: null,
      matchValue: null,
      label: 'Armes',
      icon: 'sword',
      color: '#DC2626',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
    {
      category: 'inventory',
      subcategory: 'equipment',
      itemType: 'equipment',
      matchField: null,
      matchValue: null,
      label: 'Équipement',
      icon: 'shield',
      color: '#2563EB',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
    {
      category: 'inventory',
      subcategory: 'consumable',
      itemType: 'consumable',
      matchField: null,
      matchValue: null,
      label: 'Consommables',
      icon: 'flask-conical',
      color: '#16A34A',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
    {
      category: 'inventory',
      subcategory: 'tool',
      itemType: 'tool',
      matchField: null,
      matchValue: null,
      label: 'Outils',
      icon: 'wrench',
      color: '#D97706',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
    {
      category: 'inventory',
      subcategory: 'loot',
      itemType: 'loot',
      matchField: null,
      matchValue: null,
      label: 'Trésors',
      icon: 'gem',
      color: '#EAB308',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
    {
      category: 'inventory',
      subcategory: 'container',
      itemType: 'container',
      matchField: null,
      matchValue: null,
      label: 'Conteneurs',
      icon: 'box',
      color: '#78716C',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
  ],

  // ────────────────────────────────────────
  // Pathfinder 2nd Edition
  // ────────────────────────────────────────
  'pf2e': [
    // Spells — by tradition
    {
      category: 'spell',
      subcategory: 'arcane',
      itemType: 'spell',
      matchField: 'system.traditions.value',
      matchValue: 'arcane',
      label: 'Tradition Arcanique',
      icon: 'book-open',
      color: '#60A5FA',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'spell',
      subcategory: 'divine',
      itemType: 'spell',
      matchField: 'system.traditions.value',
      matchValue: 'divine',
      label: 'Tradition Divine',
      icon: 'sun',
      color: '#FBBF24',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'spell',
      subcategory: 'occult',
      itemType: 'spell',
      matchField: 'system.traditions.value',
      matchValue: 'occult',
      label: 'Tradition Occulte',
      icon: 'moon',
      color: '#C084FC',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'spell',
      subcategory: 'primal',
      itemType: 'spell',
      matchField: 'system.traditions.value',
      matchValue: 'primal',
      label: 'Tradition Primordiale',
      icon: 'leaf',
      color: '#34D399',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'spell',
      subcategory: 'focus',
      itemType: 'spell',
      matchField: 'system.category.value',
      matchValue: 'focus',
      label: 'Sorts de Focalisation',
      icon: 'target',
      color: '#F472B6',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },

    // Features
    {
      category: 'feature',
      subcategory: 'action',
      itemType: 'action',
      matchField: null,
      matchValue: null,
      label: 'Actions',
      icon: 'zap',
      color: '#EF4444',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'feature',
      subcategory: 'feat',
      itemType: 'feat',
      matchField: null,
      matchValue: null,
      label: 'Dons',
      icon: 'award',
      color: '#F59E0B',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'feature',
      subcategory: 'ancestry_feature',
      itemType: 'heritage',
      matchField: null,
      matchValue: null,
      label: 'Traits ancestraux',
      icon: 'dna',
      color: '#14B8A6',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },

    // Inventory
    {
      category: 'inventory',
      subcategory: 'weapon',
      itemType: 'weapon',
      matchField: null,
      matchValue: null,
      label: 'Armes',
      icon: 'sword',
      color: '#DC2626',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
    {
      category: 'inventory',
      subcategory: 'armor',
      itemType: 'armor',
      matchField: null,
      matchValue: null,
      label: 'Armures',
      icon: 'shield',
      color: '#2563EB',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
    {
      category: 'inventory',
      subcategory: 'consumable',
      itemType: 'consumable',
      matchField: null,
      matchValue: null,
      label: 'Consommables',
      icon: 'flask-conical',
      color: '#16A34A',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
    {
      category: 'inventory',
      subcategory: 'equipment',
      itemType: 'equipment',
      matchField: null,
      matchValue: null,
      label: 'Équipement',
      icon: 'backpack',
      color: '#D97706',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
  ],

  // ────────────────────────────────────────
  // Warhammer Fantasy Roleplay 4e
  // ────────────────────────────────────────
  'wfrp4e': [
    {
      category: 'spell',
      subcategory: 'petty',
      itemType: 'spell',
      matchField: 'system.lore.value',
      matchValue: 'petty',
      label: 'Sorts Mineurs',
      icon: 'sparkles',
      color: '#A78BFA',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'spell',
      subcategory: 'arcane',
      itemType: 'spell',
      matchField: 'system.lore.value',
      matchValue: 'arcane',
      label: 'Sorts Arcaniques',
      icon: 'flame',
      color: '#EF4444',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'spell',
      subcategory: 'prayer',
      itemType: 'prayer',
      matchField: null,
      matchValue: null,
      label: 'Prières',
      icon: 'sun',
      color: '#FBBF24',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'feature',
      subcategory: 'talent',
      itemType: 'talent',
      matchField: null,
      matchValue: null,
      label: 'Talents',
      icon: 'award',
      color: '#F59E0B',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'inventory',
      subcategory: 'weapon',
      itemType: 'weapon',
      matchField: null,
      matchValue: null,
      label: 'Armes',
      icon: 'sword',
      color: '#DC2626',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
    {
      category: 'inventory',
      subcategory: 'armour',
      itemType: 'armour',
      matchField: null,
      matchValue: null,
      label: 'Armures',
      icon: 'shield',
      color: '#2563EB',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
    {
      category: 'inventory',
      subcategory: 'trapping',
      itemType: 'trapping',
      matchField: null,
      matchValue: null,
      label: 'Possessions',
      icon: 'backpack',
      color: '#D97706',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
  ],

  // ────────────────────────────────────────
  // Savage Worlds Adventure Edition
  // ────────────────────────────────────────
  'swade': [
    {
      category: 'spell',
      subcategory: 'power',
      itemType: 'power',
      matchField: null,
      matchValue: null,
      label: 'Pouvoirs',
      icon: 'zap',
      color: '#8B5CF6',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'feature',
      subcategory: 'edge',
      itemType: 'edge',
      matchField: null,
      matchValue: null,
      label: 'Atouts',
      icon: 'award',
      color: '#16A34A',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'feature',
      subcategory: 'hindrance',
      itemType: 'hindrance',
      matchField: null,
      matchValue: null,
      label: 'Handicaps',
      icon: 'ban',
      color: '#EF4444',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
    {
      category: 'inventory',
      subcategory: 'weapon',
      itemType: 'weapon',
      matchField: null,
      matchValue: null,
      label: 'Armes',
      icon: 'sword',
      color: '#DC2626',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
    {
      category: 'inventory',
      subcategory: 'armor',
      itemType: 'armor',
      matchField: null,
      matchValue: null,
      label: 'Armures',
      icon: 'shield',
      color: '#2563EB',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
    {
      category: 'inventory',
      subcategory: 'gear',
      itemType: 'gear',
      matchField: null,
      matchValue: null,
      label: 'Équipement',
      icon: 'backpack',
      color: '#D97706',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
  ],

  // ────────────────────────────────────────
  // Call of Cthulhu 7th Edition
  // ────────────────────────────────────────
  'CoC7': [
    {
      category: 'spell',
      subcategory: 'spell',
      itemType: 'spell',
      matchField: null,
      matchValue: null,
      label: 'Sorts',
      icon: 'book-open',
      color: '#8B5CF6',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'feature',
      subcategory: 'skill',
      itemType: 'skill',
      matchField: null,
      matchValue: null,
      label: 'Compétences',
      icon: 'brain',
      color: '#14B8A6',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
    {
      category: 'inventory',
      subcategory: 'weapon',
      itemType: 'weapon',
      matchField: null,
      matchValue: null,
      label: 'Armes',
      icon: 'sword',
      color: '#DC2626',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
    {
      category: 'inventory',
      subcategory: 'item',
      itemType: 'item',
      matchField: null,
      matchValue: null,
      label: 'Objets',
      icon: 'box',
      color: '#D97706',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
  ],

  // ────────────────────────────────────────
  // Vampire: The Masquerade 5th Edition
  // ────────────────────────────────────────
  'wod5e': [
    {
      category: 'spell',
      subcategory: 'discipline',
      itemType: 'discipline',
      matchField: null,
      matchValue: null,
      label: 'Disciplines',
      icon: 'droplet',
      color: '#DC2626',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'feature',
      subcategory: 'merit',
      itemType: 'merit',
      matchField: null,
      matchValue: null,
      label: 'Avantages',
      icon: 'award',
      color: '#16A34A',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'feature',
      subcategory: 'flaw',
      itemType: 'flaw',
      matchField: null,
      matchValue: null,
      label: 'Défauts',
      icon: 'ban',
      color: '#EF4444',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
    {
      category: 'spell',
      subcategory: 'power',
      itemType: 'power',
      matchField: null,
      matchValue: null,
      label: 'Pouvoirs',
      icon: 'flame',
      color: '#7C3AED',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'feature',
      subcategory: 'background',
      itemType: 'background',
      matchField: null,
      matchValue: null,
      label: 'Historiques',
      icon: 'scroll-text',
      color: '#D97706',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
  ],

  // ────────────────────────────────────────
  // Cyberpunk RED
  // ────────────────────────────────────────
  'cyberpunk-red-core': [
    // "Spells" — Netrunner programs
    {
      category: 'spell',
      subcategory: 'program',
      itemType: 'program',
      matchField: null,
      matchValue: null,
      label: 'Programmes',
      icon: 'terminal',
      color: '#22D3EE',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    // Features
    {
      category: 'feature',
      subcategory: 'cyberware',
      itemType: 'cyberware',
      matchField: null,
      matchValue: null,
      label: 'Cyberware',
      icon: 'cpu',
      color: '#A855F7',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'feature',
      subcategory: 'talent',
      itemType: 'talent',
      matchField: null,
      matchValue: null,
      label: 'Talents',
      icon: 'star',
      color: '#FBBF24',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'feature',
      subcategory: 'role',
      itemType: 'role',
      matchField: null,
      matchValue: null,
      label: 'Capacités de rôle',
      icon: 'user-cog',
      color: '#F472B6',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    // Inventory
    {
      category: 'inventory',
      subcategory: 'weapon',
      itemType: 'weapon',
      matchField: null,
      matchValue: null,
      label: 'Armes',
      icon: 'crosshair',
      color: '#DC2626',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
    {
      category: 'inventory',
      subcategory: 'armor',
      itemType: 'armor',
      matchField: null,
      matchValue: null,
      label: 'Armures',
      icon: 'shield',
      color: '#2563EB',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
    {
      category: 'inventory',
      subcategory: 'gear',
      itemType: 'gear',
      matchField: null,
      matchValue: null,
      label: 'Équipement',
      icon: 'backpack',
      color: '#D97706',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
  ],

  // ────────────────────────────────────────
  // Alien RPG
  // ────────────────────────────────────────
  'alienrpg': [
    // No spells in Alien RPG
    // Features
    {
      category: 'feature',
      subcategory: 'talent',
      itemType: 'talent',
      matchField: null,
      matchValue: null,
      label: 'Talents',
      icon: 'star',
      color: '#22D3EE',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'feature',
      subcategory: 'agenda',
      itemType: 'agenda',
      matchField: null,
      matchValue: null,
      label: 'Agendas',
      icon: 'clipboard-list',
      color: '#A855F7',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    // Inventory
    {
      category: 'inventory',
      subcategory: 'weapon',
      itemType: 'weapon',
      matchField: null,
      matchValue: null,
      label: 'Armes',
      icon: 'crosshair',
      color: '#DC2626',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
    {
      category: 'inventory',
      subcategory: 'armor',
      itemType: 'armor',
      matchField: null,
      matchValue: null,
      label: 'Armures',
      icon: 'shield',
      color: '#2563EB',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
    {
      category: 'inventory',
      subcategory: 'item',
      itemType: 'item',
      matchField: null,
      matchValue: null,
      label: 'Équipement',
      icon: 'backpack',
      color: '#D97706',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
  ],

  // ────────────────────────────────────────
  // Forbidden Lands
  // ────────────────────────────────────────
  'forbidden-lands': [
    // Spells
    {
      category: 'spell',
      subcategory: 'spell',
      itemType: 'spell',
      matchField: null,
      matchValue: null,
      label: 'Sorts',
      icon: 'sparkles',
      color: '#8B5CF6',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    // Features
    {
      category: 'feature',
      subcategory: 'talent',
      itemType: 'talent',
      matchField: null,
      matchValue: null,
      label: 'Talents',
      icon: 'star',
      color: '#FBBF24',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'feature',
      subcategory: 'critical_injury',
      itemType: 'criticalInjury',
      matchField: null,
      matchValue: null,
      label: 'Blessures critiques',
      icon: 'heart-crack',
      color: '#EF4444',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
    // Inventory
    {
      category: 'inventory',
      subcategory: 'weapon',
      itemType: 'weapon',
      matchField: null,
      matchValue: null,
      label: 'Armes',
      icon: 'sword',
      color: '#DC2626',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
    {
      category: 'inventory',
      subcategory: 'armor',
      itemType: 'armor',
      matchField: null,
      matchValue: null,
      label: 'Armures',
      icon: 'shield',
      color: '#2563EB',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
    {
      category: 'inventory',
      subcategory: 'gear',
      itemType: 'gear',
      matchField: null,
      matchValue: null,
      label: 'Équipement',
      icon: 'backpack',
      color: '#D97706',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
  ],

  // ────────────────────────────────────────
  // Vaesen
  // ────────────────────────────────────────
  'vaesen': [
    // Spells
    {
      category: 'spell',
      subcategory: 'spell',
      itemType: 'spell',
      matchField: null,
      matchValue: null,
      label: 'Sorts',
      icon: 'sparkles',
      color: '#8B5CF6',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'spell',
      subcategory: 'ritual',
      itemType: 'ritual',
      matchField: null,
      matchValue: null,
      label: 'Rituels',
      icon: 'flame-kindling',
      color: '#F97316',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    // Features
    {
      category: 'feature',
      subcategory: 'talent',
      itemType: 'talent',
      matchField: null,
      matchValue: null,
      label: 'Talents',
      icon: 'star',
      color: '#FBBF24',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'feature',
      subcategory: 'condition',
      itemType: 'condition',
      matchField: null,
      matchValue: null,
      label: 'Conditions',
      icon: 'alert-triangle',
      color: '#EF4444',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
    // Inventory
    {
      category: 'inventory',
      subcategory: 'weapon',
      itemType: 'weapon',
      matchField: null,
      matchValue: null,
      label: 'Armes',
      icon: 'sword',
      color: '#DC2626',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
    {
      category: 'inventory',
      subcategory: 'gear',
      itemType: 'gear',
      matchField: null,
      matchValue: null,
      label: 'Équipement',
      icon: 'backpack',
      color: '#D97706',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
  ],

  // ────────────────────────────────────────
  // Blades in the Dark
  // ────────────────────────────────────────
  'blades-in-the-dark': [
    // "Spells" — ghost/arcane abilities
    {
      category: 'spell',
      subcategory: 'ghost',
      itemType: 'ghost',
      matchField: null,
      matchValue: null,
      label: 'Pouvoirs fantômes',
      icon: 'ghost',
      color: '#A78BFA',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'spell',
      subcategory: 'ritual',
      itemType: 'ritual',
      matchField: null,
      matchValue: null,
      label: 'Rituels',
      icon: 'flame-kindling',
      color: '#F97316',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    // Features
    {
      category: 'feature',
      subcategory: 'ability',
      itemType: 'ability',
      matchField: null,
      matchValue: null,
      label: 'Capacités',
      icon: 'zap',
      color: '#FBBF24',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'feature',
      subcategory: 'crew_ability',
      itemType: 'crew_ability',
      matchField: null,
      matchValue: null,
      label: "Capacités d'équipage",
      icon: 'users',
      color: '#14B8A6',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    // Inventory
    {
      category: 'inventory',
      subcategory: 'item',
      itemType: 'item',
      matchField: null,
      matchValue: null,
      label: 'Objets',
      icon: 'backpack',
      color: '#D97706',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
  ],

  // ────────────────────────────────────────
  // Shadowrun 5e / 6e
  // ────────────────────────────────────────
  'shadowrun5e': [
    // Spells
    {
      category: 'spell',
      subcategory: 'spell',
      itemType: 'spell',
      matchField: null,
      matchValue: null,
      label: 'Sorts',
      icon: 'sparkles',
      color: '#8B5CF6',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'spell',
      subcategory: 'complex_form',
      itemType: 'complex_form',
      matchField: null,
      matchValue: null,
      label: 'Formes complexes',
      icon: 'binary',
      color: '#22D3EE',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'spell',
      subcategory: 'adept_power',
      itemType: 'adept_power',
      matchField: null,
      matchValue: null,
      label: "Pouvoirs d'adepte",
      icon: 'flame',
      color: '#F97316',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    // Features
    {
      category: 'feature',
      subcategory: 'quality',
      itemType: 'quality',
      matchField: null,
      matchValue: null,
      label: 'Qualités',
      icon: 'award',
      color: '#16A34A',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'feature',
      subcategory: 'echo',
      itemType: 'echo',
      matchField: null,
      matchValue: null,
      label: 'Échos',
      icon: 'radio',
      color: '#0EA5E9',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'feature',
      subcategory: 'metamagic',
      itemType: 'metamagic',
      matchField: null,
      matchValue: null,
      label: 'Métamagie',
      icon: 'wand-sparkles',
      color: '#A855F7',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    // Inventory
    {
      category: 'inventory',
      subcategory: 'weapon',
      itemType: 'weapon',
      matchField: null,
      matchValue: null,
      label: 'Armes',
      icon: 'crosshair',
      color: '#DC2626',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
  ],

  // ────────────────────────────────────────
  // Star Wars FFG / Genesys
  // ────────────────────────────────────────
  'starwarsffg': [
    // "Spells" — Force powers
    {
      category: 'spell',
      subcategory: 'forcepower',
      itemType: 'forcepower',
      matchField: null,
      matchValue: null,
      label: 'Pouvoirs de la Force',
      icon: 'orbit',
      color: '#60A5FA',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'spell',
      subcategory: 'power',
      itemType: 'power',
      matchField: null,
      matchValue: null,
      label: 'Pouvoirs',
      icon: 'flame',
      color: '#8B5CF6',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    // Features
    {
      category: 'feature',
      subcategory: 'talent',
      itemType: 'talent',
      matchField: null,
      matchValue: null,
      label: 'Talents',
      icon: 'star',
      color: '#FBBF24',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'feature',
      subcategory: 'specialization',
      itemType: 'specialization',
      matchField: null,
      matchValue: null,
      label: 'Spécialisations',
      icon: 'target',
      color: '#14B8A6',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'feature',
      subcategory: 'signatureability',
      itemType: 'signatureability',
      matchField: null,
      matchValue: null,
      label: 'Capacités signature',
      icon: 'badge-check',
      color: '#F472B6',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    // Inventory
    {
      category: 'inventory',
      subcategory: 'weapon',
      itemType: 'weapon',
      matchField: null,
      matchValue: null,
      label: 'Armes',
      icon: 'crosshair',
      color: '#DC2626',
      isTargetable: false,
      weight: 1,
      priority: 5,
    },
  ],

  // ────────────────────────────────────────
  // FATE Core
  // ────────────────────────────────────────
  'fate-core-official': [
    // "Spells" — Powers and Extras
    {
      category: 'spell',
      subcategory: 'power',
      itemType: 'power',
      matchField: null,
      matchValue: null,
      label: 'Pouvoirs',
      icon: 'flame',
      color: '#8B5CF6',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'spell',
      subcategory: 'extra',
      itemType: 'extra',
      matchField: null,
      matchValue: null,
      label: 'Extras',
      icon: 'plus-circle',
      color: '#0EA5E9',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    // Features
    {
      category: 'feature',
      subcategory: 'stunt',
      itemType: 'stunt',
      matchField: null,
      matchValue: null,
      label: 'Prouesses',
      icon: 'zap',
      color: '#FBBF24',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
    {
      category: 'feature',
      subcategory: 'aspect',
      itemType: 'aspect',
      matchField: null,
      matchValue: null,
      label: 'Aspects',
      icon: 'tag',
      color: '#14B8A6',
      isTargetable: true,
      weight: 1,
      priority: 5,
    },
  ],
}

// Aliases — share mappings between related system IDs
SYSTEM_MAPPINGS['vtm5e'] = SYSTEM_MAPPINGS['wod5e']
SYSTEM_MAPPINGS['shadowrun6-eden'] = SYSTEM_MAPPINGS['shadowrun5e']
SYSTEM_MAPPINGS['genesys'] = SYSTEM_MAPPINGS['starwarsffg']

export class ItemCategoryDetectionService {
  constructor(private repository: CampaignItemCategoryRuleRepository) {}

  /**
   * Detect and seed categories for a campaign based on the RPG system.
   * Idempotent: skips if rules already exist for the campaign.
   *
   * @param campaignId - The campaign UUID
   * @param systemId - Optional Foundry VTT system ID (e.g. 'dnd5e'). If not provided, tries generic detection.
   * @returns The created rules (empty array if rules already existed)
   */
  async detectAndSeedCategories(
    campaignId: string,
    systemId?: string
  ): Promise<CampaignItemCategoryRule[]> {
    // 1. Check for existing rules — don't overwrite
    const existingCount = await this.repository.countByCampaign(campaignId)
    if (existingCount > 0) {
      return this.repository.findByCampaign(campaignId)
    }

    // 2. Resolve system mappings
    const seeds = this.getSeedsForSystem(systemId)
    if (seeds.length === 0) {
      return []
    }

    // 3. Bulk-insert the rules
    const rulesData = seeds.map((seed, index) => ({
      campaignId,
      category: seed.category,
      subcategory: seed.subcategory,
      itemType: seed.itemType,
      matchField: seed.matchField,
      matchValue: seed.matchValue,
      label: seed.label,
      description: null,
      icon: seed.icon,
      color: seed.color,
      isTargetable: seed.isTargetable,
      weight: seed.weight,
      priority: seed.priority + index, // Ensure unique priority ordering
      isEnabled: true,
    }))

    return this.repository.createMany(rulesData)
  }

  /**
   * Returns the pre-configured seeds for a known system, or an empty array for unknown systems.
   */
  private getSeedsForSystem(systemId?: string): CategorySeed[] {
    if (!systemId) return []
    return SYSTEM_MAPPINGS[systemId] ?? []
  }

  /**
   * Returns the list of supported RPG system IDs.
   */
  static getSupportedSystems(): string[] {
    return Object.keys(SYSTEM_MAPPINGS)
  }

  /**
   * Check if a system ID has pre-configured mappings.
   */
  static isSystemSupported(systemId: string): boolean {
    return systemId in SYSTEM_MAPPINGS
  }
}

export default ItemCategoryDetectionService
